### ISSUE TITLE
Pipe run

### ISSUE THREAD

**Issue by sararselitsky** [yanailab/CEL-Seq-pipeline#14]
I'm trying to understand your pipeline. Is there a place with more information than the README and the papers? For instance, what is the "pipe_run" parameter?

**Comment by Puriney** [comment]
Thanks for your interest. The `pipe_run` parameter you asked must be the one inside <kbd>config_file_example.txt</kbd>. This is a binary flag (True/False) to denote whether the step is going to run.

For example, [here](https://github.com/yanailab/CEL-Seq-pipeline/blob/133912cd4ceb20af0c67627ab883dfce8b9668df/config_file_example.txt#L26) `pipe_run = True`  means `bowtie_wrapper` step is going to run, whereas `bc_demultiplex` is not.

A new version of CEL-Seq2 package is going to be released in 1-2 weeks. It features in computational efficiency and being user-friendly. Stay in tuned.

**Comment by sararselitsky** [comment]
Thank you! I'll look out for the new release.
