### ISSUE TITLE
Sample sheet?

### ISSUE THREAD

**Issue by dmarron** [yanailab/CEL-Seq-pipeline#15]
I have a question about how to properly fill out the sample sheet to run CEL-Seq.  The repository has an example sample sheet which I am using as a template.  It has the fields ID, flocell, series, lane, il_barcode, cel_barcode, and project.  I'm assuming il_barcode is the illumina barcode and cel_barcode is the umi barcode, but the example sample sheet has integer values for those fields and I was wondering what those mean.  When the example has "4" for il_barcode, what does that 4 represent?  And what do the 1-18 values on cel_barcode represent?  And what does series mean?  Also, can ID and project be anything as long as they are different?

Thanks,
David

**Comment by Puriney** [comment]
> I have a question about how to properly fill out the sample sheet to run CEL-Seq. The repository has an example sample sheet which I am using as a template. It has the fields ID, flocell, series, lane, il_barcode, cel_barcode, and project. 

The motivation is to automatically infer the path of inputs, since Illumina sequencer has a consistent naming scheme.

> I'm assuming il_barcode is the illumina barcode and cel_barcode is the umi barcode, but the example sample sheet has integer values for those fields and I was wondering what those mean. 

cel_barcode stands for the barcode for cells.

>When the example has "4" for il_barcode, what does that 4 represent?

It means 4th illumina sequencing barcode in use.

>And what do the 1-18 values on cel_barcode represent?

It means No. 1-18 in cell barcode dictionary: https://github.com/yanailab/CEL-Seq-pipeline/blob/stable/barcode_umis.tab

>And what does series mean? 

`series` helps to define the complexed experiment design when biological/technical replicates are present.

>Also, can ID and project be anything as long as they are different?

`#id` and `project` is also to help assign the cell to its experiment source.

**Comment by Puriney** [comment]
Thanks for your interest in our tool. There is a good news that our group is going to release a new version of pipline to process CEL-Seq2 data, which is more user-friendly. Hopefully it will come out next week. Stay tuned ;-)

**Comment by dmarron** [comment]
Thank you for responding to my question.  The answer helped me construct the sample sheet, but I have still have issues running the software (it ends up putting all reads into undetermined and leaving the split fastq files empty when splitting by barcodes).  I have been waiting for the new version to release to hopefully fix this problem.  Do you have any news on the new version?

Thanks,
David

**Comment by Puriney** [comment]
New version is here: <https://github.com/yanailab/celseq2>
