### ISSUE TITLE
install of celseq2

### ISSUE THREAD

**Issue by yueli8** [yanailab/CEL-Seq-pipeline#17]
Hello, 

Thank you for developing so nice software!

I tried to install `celseq2` in my Ubuntu `system`.

```
~/celseq2-master$ pip install ./
Defaulting to user installation because normal site-packages is not writeable
Processing /home/li/celseq2-master

```

But it comes out:

`ERROR: xlmhg 2.5.4 has requirement plotly>=3, but you'll have plotly 2.7.0 which is incompatible.`

Thanks in advance for any great help!

Best,

Yue

**Comment by yueli8** [comment]
`li@Pavilion-Desktop-590-p0xxx:~$ pip install plotly`

**Comment by Puriney** [comment]
You need upgrade plotly.
