### ISSUE TITLE
install of CEL-Seq-pipeline

### ISSUE THREAD

**Issue by yueli8** [yanailab/CEL-Seq-pipeline#18]
Hello,

Thank you so  much for developing so nice software!

I downloaded `CEL-Seq-pipeline-stable.zip` from https://github.com/yanailab/CEL-Seq-pipeline
unzipped.

```
li@lx:~/CEL-Seq-pipeline-stable$ python pijpleiding.py --help
Traceback (most recent call last):
  File "pijpleiding.py", line 31, in <module>
    import bowtie_wrapper, bc_demultiplex, htseq_wrapper, clean_up
  File "/home/li/CEL-Seq-pipeline-stable/bc_demultiplex.py", line 22, in <module>
    from HTSeq import FastqReader, SequenceWithQualities
ImportError: No module named HTSeq
avilion-Desktop-59
```
My python version is:

```li@lx:~/CEL-Seq-pipeline-stable$ python --version
Python 2.7.15+
```
 
I worked in `Ubuntu` system.

Thank you in advance for your great help and I really appreciated！

Best,

Yue

**Comment by yueli8** [comment]
`li@0xxx:~$ sudo apt-get install build-essential python2.7-dev python-numpy python-matplotlib python-pysam python-htseq`

**Comment by Puriney** [comment]
If possible, could you use conda or pip to install HTSeq instead? It seems your system did not find the path to HTSeq. 

https://github.com/simon-anders/htseq
