### ISSUE TITLE
all the test_out file are 0 bytes

### ISSUE THREAD

**Issue by yueli8** [yanailab/CEL-Seq-pipeline#19]
Hello,

I tried to use be_demultiplex from: https://github.com/yanailab/CEL-Seq-pipeline.

All the output files are 0 bytes.

Thanks in advance for any great help!

Best,

Yue

```
li@Desktop-590-p0xxx:~/CEL-Seq-pipeline-stable$ bc_demultiplex --out-dir test_out --bc-index tmp01 --not-gzip R1.fq R2.fq
[ Sat Mar  7 00:42:58 2020 ] Demultiplexing starts R1.fq--R2.fq ...

[ Sat Mar  7 00:42:58 2020 ] Demultiplexing ends R1.fq--R2.fq.

```
[R1.zip](https://github.com/yanailab/CEL-Seq-pipeline/files/4301419/R1.zip)
[R2.zip](https://github.com/yanailab/CEL-Seq-pipeline/files/4301420/R2.zip)
[tmp01.zip](https://github.com/yanailab/CEL-Seq-pipeline/files/4301421/tmp01.zip)

**Comment by Puriney** [comment]
`bc_demultiplex` is a sub-tool in `celseq2` pipeline rather than the previous pipeline CEL-Seq-pipeline. 

When users do CEL-Seq2 experiment, they should really know which cell barcodes are used to label cells. This is done by specifying the `--bc-index` parameter when running the `bc_demultiplex` command.  Here, the parameter is missing in your run so as expected it gives you nothing.

Actually, the `bc_demultiplex` command is not supposed to be called by common users.

**Comment by yueli8** [comment]
Hello, Puriney,

Thank you so much for your detailed explanation!

Would you please tell me what the format of --bc-index should be?

Thank you in advance for your great help!

Best,

Yue

Please see attached file of R1.fa and R2.fq.



li@590-p0xxx:~/celseq2-master$ bc_demultiplex --out-dir test_out --bc-index tmp01 --not-gzip R1.fq R2.fq
[ Thu Mar 12 23:38:13 2020 ] Demultiplexing starts R1.fq--R2.fq ...

[ Thu Mar 12 23:38:13 2020 ] Demultiplexing ends R1.fq--R2.fq.




li@590-p0xxx:~/celseq2-master$  head -n 20 R1.fq 
@MN00336:7:00CELSEQ2:1:78888:10964:367 1:N:0:ATGCGC
AAAAAAAGACTC
+
,@/9?C9:+86E
@MN00336:7:00CELSEQ2:1:20266:32663:7 1:N:0:ATGCGC
AAAAATAGACTC
+
.-?/D.;8,+GI
@MN00336:2:00CELSEQ2:1:42122:46947:341 1:N:0:ATGCGC
AAAAAAAGACTC
+
.1<76.0.4;;/
@MN00336:3:00CELSEQ2:1:2947:82398:365 1:N:0:ATGCGC
AAAAATAGACTC
+
6C@84C296I2=
@MN00336:2:00CELSEQ2:1:26531:96421:673 1:N:0:ATGCGC
AAAAAAAGACTC
+
1E7,>-FG>2C,


li@590-p0xxx:~/celseq2-master$ head -n 20 R2.fq 
@MN00336:7:00CELSEQ2:1:78888:10964:367 2:N:0:ATGCGC
TTCTCAAAAACTATCCTGTCTCAGCACGAATCTTCGAAAATGCCTATCTA
+
;B80ED6-::B=:<6,,HE4F;.E=G@->CF5;@0EC,=60=I<.:CHA,
@MN00336:7:00CELSEQ2:1:20266:32663:7 2:N:0:ATGCGC
CACGTGGGATCAGTAATGGGTTGCCACGCGTTAACGTTCCGTCCTATAAG
+
.AIGF5A:H@EE6A-1H7@<3=G5500D@H?H1016I19,+;>:GEH<3/
@MN00336:2:00CELSEQ2:1:42122:46947:341 2:N:0:ATGCGC
TTCTCAAAAACTATCCTGTCTCAGCACGAATCTTCGAAAATGCCTATCTA
+
22-9HDC954+1I/<8AI4HB:<88D->@A/B?C>-B?01CD,0I7,9@:
@MN00336:3:00CELSEQ2:1:2947:82398:365 2:N:0:ATGCGC
CACGTGGGATCAGTAATGGGTTGCCACGCGTTAACGTTCCGTCCTATAAG
+
;,0FC10H=AG3:G02FE:/D4B2/@76899?.?:D3?1@@;9H6-5,FD
@MN00336:2:00CELSEQ2:1:26531:96421:673 2:N:0:ATGCGC
GATGCATTGACATGGAGCTGATGGGCCGACTCCCATTAAGGGGTCTCTCC
+
.4-F?D?13=C>4C7>E?9=18D:+D/,<B.89.>2@:;2B+4.-+;-.8
